### ISSUE TITLE
Unable to run dev

### ISSUE THREAD

**Issue by Sripaad** [MeryllEssig/vscode-glyph-theme#1]
@MeryllEssig 
Hey Ive cloned the repo and made a few changes to the yaml file, 
went on to run `node ./scripts/dev.js` which returns this error.
```
vscode-glyph-theme/scripts/build.js:14
async function build() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
lemme know what am doing wrong, also ive updated node, running MacOSX.

**Comment by Sripaad** [comment]
Fixed it, issue is no longer valid. Closing it
